###
# updates the APT package cache and install necessary packages
#
---

- name: ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes

- name: ensure web server packages are installed
  apt: name={{item}} state=latest update_cache=true
  sudo: yes
  with_items:
    - rabbitmq-server
